# Generated by Django 5.1.4 on 2025-01-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بازیگر')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('nationality', models.CharField(max_length=50, verbose_name='ملیت')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, verbose_name='نام ژانر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('release_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('duration', models.PositiveIntegerField(verbose_name='مدت زمان (دقیقه)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('poster_url', models.URLField(blank=True, null=True, verbose_name='پوستر')),
                ('language', models.CharField(max_length=50, verbose_name='زبان')),
                ('age_rating', models.CharField(max_length=10, verbose_name='رده سنی')),
            ],
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='نقش بازیگر')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.actor', verbose_name='بازیگر')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='فیلم')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre', verbose_name='ژانر')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='فیلم')),
            ],
        ),
    ]
