# Generated by Django 5.1.4 on 2025-01-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_country_movie_overall_rating_favoritemovie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام برچسب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], max_length=20, verbose_name='کیفیت')),
                ('download_url', models.URLField(verbose_name='لینک دانلود')),
                ('file_size', models.CharField(blank=True, max_length=10, verbose_name='حجم فایل')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='فیلم')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='زبان زیرنویس')),
                ('subtitle_file', models.URLField(verbose_name='فایل زیرنویس')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='فیلم')),
            ],
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='فیلم')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag', verbose_name='برچسب')),
            ],
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('2k', '2k'), ('4K', '4K')], max_length=20, verbose_name='کیفیت')),
                ('stream_url', models.URLField(verbose_name='لینک پخش آنلاین')),
                ('download_url', models.URLField(verbose_name='لینک دانلود')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='فیلم')),
            ],
        ),
    ]
