# Generated by Django 5.1.4 on 2025-01-08 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('G', 'General Audiences (همه سنین)'), ('PG', 'Parental Guidance (مشورت والدین)'), ('PG-13', 'Parents Strongly Cautioned (13+ با مشورت)'), ('R', 'Restricted (17+ با محدودیت)'), ('NC-17', 'No Children Under 17 (غیرقابل مشاهده برای زیر 17)')], default='G', max_length=50, unique=True, verbose_name='رده\u200cبندی سنی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کارگردان')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('nationality', models.CharField(max_length=50, verbose_name='ملیت')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agerating', verbose_name='رده\u200cبندی سنی'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=True, verbose_name='لایک شده')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='فیلم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.director', verbose_name='کارگردان')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='فیلم')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام لیست پخش')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='فیلم')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist', verbose_name='لیست پخش')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پیشنهاد')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='فیلم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(verbose_name='شماره فصل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='سریال')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField(verbose_name='شماره قسمت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان قسمت')),
                ('duration', models.PositiveIntegerField(verbose_name='مدت زمان (دقیقه)')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.season', verbose_name='فصل')),
            ],
        ),
        migrations.CreateModel(
            name='UserGenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_level', models.PositiveIntegerField(verbose_name='سطح علاقه (1 تا 5)')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre', verbose_name='ژانر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
