# Generated by Django 5.1.4 on 2025-01-10 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL, verbose_name='علاقه\u200cمندی\u200cها'),
        ),
    ]
