# Generated by Django 5.1.4 on 2025-01-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_movie_poster_image_alter_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='main.genre', verbose_name='ژانرها'),
        ),
    ]
