# Generated by Django 5.1.4 on 2025-01-10 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_animation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animation',
            options={},
        ),
        migrations.RemoveField(
            model_name='animation',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='series',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='series',
            name='rating',
        ),
        migrations.AddField(
            model_name='animation',
            name='age_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agerating', verbose_name='رده\u200cبندی سنی'),
        ),
        migrations.AddField(
            model_name='animation',
            name='country',
            field=models.CharField(default='United States', max_length=100, verbose_name='کشور تولید'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animation',
            name='duration',
            field=models.PositiveIntegerField(default=120, verbose_name='مدت زمان (دقیقه)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animation',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_animations', to=settings.AUTH_USER_MODEL, verbose_name='علاقه\u200cمندی\u200cها'),
        ),
        migrations.AddField(
            model_name='animation',
            name='genres',
            field=models.ManyToManyField(related_name='animations', to='main.genre', verbose_name='ژانرها'),
        ),
        migrations.AddField(
            model_name='animation',
            name='language',
            field=models.CharField(default='English', max_length=50, verbose_name='زبان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animation',
            name='overall_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='امتیاز کلی'),
        ),
        migrations.AddField(
            model_name='animation',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='پوستر (تصویر)'),
        ),
        migrations.AddField(
            model_name='animation',
            name='poster_url',
            field=models.URLField(blank=True, null=True, verbose_name='پوستر (لینک)'),
        ),
        migrations.AddField(
            model_name='animation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddField(
            model_name='animation',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AddField(
            model_name='series',
            name='age_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agerating', verbose_name='رده\u200cبندی سنی'),
        ),
        migrations.AddField(
            model_name='series',
            name='country',
            field=models.CharField(default='United States', max_length=100, verbose_name='کشور تولید'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='duration',
            field=models.PositiveIntegerField(default=120, verbose_name='مدت زمان هر قسمت (دقیقه)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_series', to=settings.AUTH_USER_MODEL, verbose_name='علاقه\u200cمندی\u200cها'),
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(related_name='series', to='main.genre', verbose_name='ژانرها'),
        ),
        migrations.AddField(
            model_name='series',
            name='language',
            field=models.CharField(default='English', max_length=50, verbose_name='زبان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='overall_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='امتیاز کلی'),
        ),
        migrations.AddField(
            model_name='series',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='پوستر (تصویر)'),
        ),
        migrations.AddField(
            model_name='series',
            name='poster_url',
            field=models.URLField(blank=True, null=True, verbose_name='پوستر (لینک)'),
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddField(
            model_name='series',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='description',
            field=models.TextField(default='none', verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(default='none', verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='release_date',
            field=models.DateField(default='2025-01-10', verbose_name='تاریخ انتشار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان سریال'),
        ),
    ]
