# Generated by Django 5.1.4 on 2025-01-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_animation_options_remove_animation_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سال پایان'),
        ),
        migrations.AddField(
            model_name='series',
            name='episodes',
            field=models.PositiveIntegerField(default=3, verbose_name='تعداد قسمت\u200cها'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='seasons',
            field=models.PositiveIntegerField(default=3, verbose_name='تعداد فصل\u200cها'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='start_year',
            field=models.PositiveIntegerField(default=2008, verbose_name='سال شروع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.CharField(choices=[('ongoing', 'در حال پخش'), ('ended', 'تمام شده')], default='ended', max_length=20, verbose_name='وضعیت پخش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='release_date',
            field=models.DateField(verbose_name='تاریخ انتشار اولین قسمت'),
        ),
    ]
