# Generated by Django 5.1.4 on 2025-01-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_movie_directors_movie_stars_series_directors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='background_poster',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='پوستر پس\u200cزمینه'),
        ),
        migrations.AddField(
            model_name='movie',
            name='background_poster',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='پوستر پس\u200cزمینه'),
        ),
        migrations.AddField(
            model_name='series',
            name='background_poster',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='پوستر پس\u200cزمینه'),
        ),
    ]
