# Generated by Django 5.1.4 on 2025-01-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_animation_background_poster_movie_background_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تریلر'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تریلر'),
        ),
        migrations.AddField(
            model_name='series',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تریلر'),
        ),
    ]
