# Generated by Django 5.1.4 on 2025-01-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_animation_trailer_url_movie_trailer_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='trailer_video',
            field=models.FileField(blank=True, null=True, upload_to='trailers/', verbose_name='ویدئو تریلر'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_video',
            field=models.FileField(blank=True, null=True, upload_to='trailers/', verbose_name='ویدئو تریلر'),
        ),
        migrations.AddField(
            model_name='series',
            name='trailer_video',
            field=models.FileField(blank=True, null=True, upload_to='trailers/', verbose_name='ویدئو تریلر'),
        ),
    ]
