# Generated by Django 5.1.4 on 2025-01-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_subscription_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='download_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='file_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='main.movie'),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='quality',
            field=models.CharField(choices=[('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], max_length=20),
        ),
    ]
