# Generated by Django 5.1.4 on 2025-01-24 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_downloadlink_download_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.animation'),
        ),
        migrations.AddField(
            model_name='review',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.series'),
        ),
    ]
