# Generated by Django 5.1.4 on 2025-01-24 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_review_animation_review_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlink',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.animation'),
        ),
        migrations.AddField(
            model_name='downloadlink',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.series'),
        ),
    ]
