# Generated by Django 5.1.4 on 2026-09-12 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _copy_favorite_movies(apps, schema_editor):
    FavoriteMovie = apps.get_model('main', 'FavoriteMovie')
    FavoriteItem = apps.get_model('main', 'FavoriteItem')
    for row in FavoriteMovie.objects.all():
        FavoriteItem.objects.get_or_create(user_id=row.user_id, movie_id=row.movie_id)


def _copy_replies_to_reviews(apps, schema_editor):
    Reply = apps.get_model('main', 'Reply')
    Review = apps.get_model('main', 'Review')
    for reply in Reply.objects.all():
        if not reply.review_id:
            continue
        parent = Review.objects.filter(id=reply.review_id).first()
        if not parent:
            continue
        Review.objects.create(
            user_id=reply.user_id,
            movie_id=parent.movie_id,
            series_id=parent.series_id,
            animation_id=parent.animation_id,
            parent_id=parent.id,
            rating=parent.rating or 1,
            review_text=reply.reply_text,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_phase0_nullable_targets_favorite_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_items', to='main.animation'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_items', to='main.movie'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_items', to='main.series'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            code=_copy_favorite_movies,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='favoritemovie',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movieactor',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movieactor',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviedirector',
            name='director',
        ),
        migrations.RemoveField(
            model_name='moviedirector',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movietag',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movietag',
            name='tag',
        ),
        migrations.RunPython(
            code=_copy_replies_to_reviews,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent_reply',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode_number']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['season_number']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'verbose_name_plural': 'Watch histories'},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='animation',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='season',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='series',
            name='favorites',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='episodes',
            new_name='episode_count',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='seasons',
            new_name='season_count',
        ),
        migrations.AddField(
            model_name='animation',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='animations', to='main.director', verbose_name='کارگردان\u200cها'),
        ),
        migrations.AddField(
            model_name='animation',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='animations', to='main.actor', verbose_name='بازیگران'),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_list', to='main.series', verbose_name='سریال'),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.animation'),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.series'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='main.animation'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='main.series'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='age_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agerating', verbose_name='رده\u200cبندی سنی'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='language',
            field=models.CharField(db_index=True, max_length=50, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='overall_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='امتیاز کلی'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='main.animation'),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='main.series'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='main.season', verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام ژانر'),
        ),
        migrations.AlterField(
            model_name='like',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.movie'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agerating', verbose_name='رده\u200cبندی سنی'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(db_index=True, max_length=50, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overall_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='امتیاز کلی'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.playlist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.animation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.series'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='series',
            name='age_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agerating', verbose_name='رده\u200cبندی سنی'),
        ),
        migrations.AlterField(
            model_name='series',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='مدت زمان (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='series',
            name='language',
            field=models.CharField(db_index=True, max_length=50, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='series',
            name='overall_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='امتیاز کلی'),
        ),
        migrations.AlterField(
            model_name='series',
            name='release_date',
            field=models.DateField(verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='series',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='main.movie'),
        ),
        migrations.AlterField(
            model_name='usergenrepreference',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre'),
        ),
        migrations.AlterField(
            model_name='usergenrepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_qualities', to='main.movie'),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='quality',
            field=models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('2k', '2k'), ('4K', '4K')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='watch_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='main.movie'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='animation',
            index=models.Index(fields=['title'], name='main_animat_title_a0052c_idx'),
        ),
        migrations.AddIndex(
            model_name='animation',
            index=models.Index(fields=['-release_date'], name='main_animat_release_890d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='animation',
            index=models.Index(fields=['-view_count'], name='main_animat_view_co_cc1b45_idx'),
        ),
        migrations.AddIndex(
            model_name='animation',
            index=models.Index(fields=['-overall_rating'], name='main_animat_overall_cde0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='main_movie_title_508b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-release_date'], name='main_movie_release_a99c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-view_count'], name='main_movie_view_co_b5d5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-overall_rating'], name='main_movie_overall_566d42_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-sent_date'], name='main_notifi_user_id_ea1253_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['movie', 'parent'], name='main_review_movie_i_a8765d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['series', 'parent'], name='main_review_series__510de5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['animation', 'parent'], name='main_review_animati_78b65b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-review_date'], name='main_review_user_id_b95e48_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['title'], name='main_series_title_50a6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['-release_date'], name='main_series_release_3ca089_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['-view_count'], name='main_series_view_co_af78dc_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['-overall_rating'], name='main_series_overall_d23f43_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['-start_year'], name='main_series_start_y_e9e758_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'is_active', '-end_date'], name='main_subscr_user_id_5238f9_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', '-transaction_date'], name='main_wallet_user_id_7ffdc6_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['user', '-watch_datetime'], name='main_watchh_user_id_dca3de_idx'),
        ),
        migrations.AddConstraint(
            model_name='downloadlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animation__isnull', True), ('movie__isnull', False), ('series__isnull', True)), models.Q(('animation__isnull', True), ('movie__isnull', True), ('series__isnull', False)), models.Q(('animation__isnull', False), ('movie__isnull', True), ('series__isnull', True)), _connector='OR'), name='downloadlink_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('season', 'episode_number'), name='unique_season_episode_number'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie_like'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(fields=('playlist', 'movie'), name='unique_playlist_movie'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_recommendation'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 10)), name='review_rating_range_1_10'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animation__isnull', True), ('movie__isnull', False), ('series__isnull', True)), models.Q(('animation__isnull', True), ('movie__isnull', True), ('series__isnull', False)), models.Q(('animation__isnull', False), ('movie__isnull', True), ('series__isnull', True)), _connector='OR'), name='review_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('series', 'season_number'), name='unique_series_season_number'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.CheckConstraint(condition=models.Q(('end_year__isnull', True), ('end_year__gte', models.F('start_year')), _connector='OR'), name='series_end_year_gte_start_year'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='subscription_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='usergenrepreference',
            constraint=models.UniqueConstraint(fields=('user', 'genre'), name='unique_user_genre_preference'),
        ),
        migrations.AddConstraint(
            model_name='usergenrepreference',
            constraint=models.CheckConstraint(condition=models.Q(('preference_level__gte', 1), ('preference_level__lte', 5)), name='preference_level_1_5'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallet_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animation__isnull', True), ('movie__isnull', False), ('series__isnull', True)), models.Q(('animation__isnull', True), ('movie__isnull', True), ('series__isnull', False)), models.Q(('animation__isnull', False), ('movie__isnull', True), ('series__isnull', True)), _connector='OR'), name='watchlist_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('user', 'movie'), name='unique_user_watchlist_movie'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('user', 'series'), name='unique_user_watchlist_series'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(condition=models.Q(('animation__isnull', False)), fields=('user', 'animation'), name='unique_user_watchlist_animation'),
        ),
        migrations.DeleteModel(
            name='FavoriteMovie',
        ),
        migrations.DeleteModel(
            name='MovieActor',
        ),
        migrations.DeleteModel(
            name='MovieDirector',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
        migrations.DeleteModel(
            name='MovieTag',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddConstraint(
            model_name='favoriteitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animation__isnull', True), ('movie__isnull', False), ('series__isnull', True)), models.Q(('animation__isnull', True), ('movie__isnull', True), ('series__isnull', False)), models.Q(('animation__isnull', False), ('movie__isnull', True), ('series__isnull', True)), _connector='OR'), name='favorite_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='favoriteitem',
            constraint=models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('user', 'movie'), name='unique_user_favorite_movie'),
        ),
        migrations.AddConstraint(
            model_name='favoriteitem',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('user', 'series'), name='unique_user_favorite_series'),
        ),
        migrations.AddConstraint(
            model_name='favoriteitem',
            constraint=models.UniqueConstraint(condition=models.Q(('animation__isnull', False)), fields=('user', 'animation'), name='unique_user_favorite_animation'),
        ),
    ]
