# Generated by Django 5.1.4 on 2026-09-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_phase1_domain_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='episode_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد قسمت\u200cها'),
        ),
        migrations.AlterField(
            model_name='series',
            name='season_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فصل\u200cها'),
        ),
    ]
