# Generated by Django 5.1.4 on 2026-09-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_phase2_audit_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='ai_enriched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان غنی\u200cسازی AI'),
        ),
        migrations.AddField(
            model_name='animation',
            name='ai_summary',
            field=models.TextField(blank=True, default='', verbose_name='خلاصه هوشمند'),
        ),
        migrations.AddField(
            model_name='animation',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cهای هوشمند'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ai_enriched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان غنی\u200cسازی AI'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ai_summary',
            field=models.TextField(blank=True, default='', verbose_name='خلاصه هوشمند'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cهای هوشمند'),
        ),
        migrations.AddField(
            model_name='series',
            name='ai_enriched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان غنی\u200cسازی AI'),
        ),
        migrations.AddField(
            model_name='series',
            name='ai_summary',
            field=models.TextField(blank=True, default='', verbose_name='خلاصه هوشمند'),
        ),
        migrations.AddField(
            model_name='series',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cهای هوشمند'),
        ),
    ]
