# Generated by Django 5.2.17 on 2026-09-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_phase5_ai_enrichment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='country',
            field=models.CharField(db_index=True, max_length=100, verbose_name='کشور تولید'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(db_index=True, max_length=100, verbose_name='کشور تولید'),
        ),
        migrations.AlterField(
            model_name='series',
            name='country',
            field=models.CharField(db_index=True, max_length=100, verbose_name='کشور تولید'),
        ),
        migrations.AlterField(
            model_name='series',
            name='status',
            field=models.CharField(choices=[('ongoing', 'در حال پخش'), ('ended', 'تمام شده')], db_index=True, max_length=20, verbose_name='وضعیت پخش'),
        ),
    ]
